export type Locale = "zh" | "en";

export { stories } from "./articles";
export type { Story } from "./articles";

export const copy = {
  zh: {
    nav: { home: "首页", stories: "文章", about: "关于", subscribe: "订阅" },
    controls: { language: "切换到英文", theme: "切换主题", menu: "打开菜单", close: "关闭菜单" },
    search: {
      label: "搜索文章",
      placeholder: "搜索标题或正文",
      close: "关闭搜索",
      clear: "清除搜索内容",
      latest: "最近文章",
      results: "搜索结果",
      noResults: "没有找到相关内容。",
      viewAll: "查看全部结果",
    },
    hero: {
      eyebrow: "关于设计、技术与文化的独立笔记。",
      lines: ["万象志"],
      lead: "关于设计、技术与日常的独立笔记。",
      issue: "第 024 期",
      month: "2026 年 8 月",
      place: "上海 / 新加坡",
    },
    sections: {
      featured: "本期精选",
      latest: "最新文章",
      archive: "文章索引",
      statement: "编辑手记",
      allStories: "所有文章",
    },
    actions: { read: "阅读文章", viewAll: "查看全部", back: "返回文章", goHome: "回到首页" },
    statement: "我相信好的数字产品也可以安静。它不争抢注意力，只在需要时给出清晰、诚实而有分寸的回应。",
    newsletter: {
      eyebrow: "不定期来信",
      title: "把值得慢读的内容，寄到你的邮箱。",
      text: "每月一至两封。没有追踪，没有噪音，随时可以离开。",
      label: "邮箱地址",
      placeholder: "name@example.com",
      button: "订阅",
      submitting: "提交中…",
      success: "订阅已保存。下一封信见。",
      error: "暂时无法订阅，请稍后重试。",
    },
    storiesPage: {
      eyebrow: "ARCHIVE / 2026",
      title: "文章存档",
      intro: "按时间整理关于设计、技术、编辑与文化的长期笔记。",
      allCategories: "全部",
      empty: "这个分类还没有文章。",
      searchLabel: "搜索文章",
      searchPlaceholder: "搜索标题、摘要或正文",
      noResults: "没有找到相关内容。",
      resultCount: "篇结果",
      clearSearch: "清除搜索",
    },
    about: {
      eyebrow: "关于 / 万象志",
      title: "观察，\n然后记录。",
      lead: "万象志，关注设计、技术与日常。",
      principlesTitle: "写作原则",
      principles: [
        ["01", "先理解", "事实先于观点。"],
        ["02", "说清楚", "准确，不卖弄。"],
        ["03", "少打扰", "尊重每次阅读。"],
      ],
    },
    article: { share: "分享", next: "下一篇", published: "发布于", contents: "目录" },
    footer: { note: "独立写作，安静发布。", rights: "© 2026 Omni Journal" },
    notFound: { eyebrow: "404", title: "这一页还没有被写下。", text: "链接可能已移动，或者这篇文章仍在路上。" },
  },
  en: {
    nav: { home: "Home", stories: "Stories", about: "About", subscribe: "Subscribe" },
    controls: { language: "Switch to Chinese", theme: "Switch theme", menu: "Open menu", close: "Close menu" },
    search: {
      label: "Search stories",
      placeholder: "Search stories",
      close: "Close search",
      clear: "Clear search",
      latest: "Latest stories",
      results: "Search results",
      noResults: "No matching stories found.",
      viewAll: "View all results",
    },
    hero: {
      eyebrow: "Independent notes on design, technology & culture.",
      lines: ["OMNI JOURNAL"],
      lead: "Independent notes on design, technology, and daily life.",
      issue: "Issue 024",
      month: "August 2026",
      place: "Shanghai / Singapore",
    },
    sections: {
      featured: "Featured stories",
      latest: "Latest stories",
      archive: "The archive",
      statement: "Editor’s note",
      allStories: "All stories",
    },
    actions: { read: "Read story", viewAll: "View all", back: "Back to stories", goHome: "Go home" },
    statement: "I believe good digital products can be quiet. They do not compete for attention; they respond with clarity, honesty, and restraint when needed.",
    newsletter: {
      eyebrow: "AN OCCASIONAL LETTER",
      title: "Slow ideas, delivered to your inbox.",
      text: "One or two notes a month. No tracking, no noise, and an easy way out.",
      label: "Email address",
      placeholder: "name@example.com",
      button: "Subscribe",
      submitting: "Submitting…",
      success: "Subscription saved. See you in the next letter.",
      error: "Subscription is temporarily unavailable. Please try again.",
    },
    storiesPage: {
      eyebrow: "ARCHIVE / 2026",
      title: "Archive",
      intro: "Long-running notes on design, technology, editorial thinking, and culture — ordered by time.",
      allCategories: "All",
      empty: "There are no stories in this category yet.",
      searchLabel: "Search stories",
      searchPlaceholder: "Search titles, summaries, or full text",
      noResults: "No matching stories found.",
      resultCount: "results",
      clearSearch: "Clear search",
    },
    about: {
      eyebrow: "ABOUT / OMNI",
      title: "Observe.\nThen write.",
      lead: "Omni Journal covers design, technology, and everyday life.",
      principlesTitle: "How I write",
      principles: [
        ["01", "Understand first", "Facts before opinions."],
        ["02", "Stay clear", "Precision over jargon."],
        ["03", "Respect attention", "No noise. No endless feeds."],
      ],
    },
    article: { share: "Share", next: "Next story", published: "Published", contents: "Contents" },
    footer: { note: "Independently written. Quietly published.", rights: "© 2026 Omni Journal" },
    notFound: { eyebrow: "404", title: "This page has not been written yet.", text: "The link may have moved, or the story may still be on its way." },
  },
} as const;

export const formatDate = (date: string, locale: Locale) =>
  new Intl.DateTimeFormat(locale === "zh" ? "zh-CN" : "en-US", {
    month: locale === "zh" ? "2-digit" : "short",
    day: "2-digit",
    year: locale === "zh" ? undefined : "numeric",
  }).format(new Date(`${date}T00:00:00`));
